# See documentation
#
#   http://goreleaser.com
#
# Usage:
#
#  GIT_SUMMARY=$(git describe --tags --dirty --always) goreleaser --rm-dist --skip-publish
#
project_name: run
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    # - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    binary: run
    ldflags:
      - -s -w -X "main.Version={{.Version}}" -X "main.BuildDate={{.Date}}" -X "main.GitSummary={{.Env.GIT_SUMMARY}}" -X "main.BuildTool=goreleaser"
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm64
archives:
  - replacements:
      darwin: darwin
      linux: linux
      amd64: amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort:
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  draft: true
  github:
    owner: TekWizely
    name: run
